package com.pridesys.ticketing.issue.service.impl;

import com.pridesys.ticketing.dto.*;
import com.pridesys.ticketing.entity.*;
import com.pridesys.ticketing.issue.service.IIssueService;
import com.pridesys.ticketing.repository.*;
import org.springframework.data.domain.*;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;

@Service
public class IssueServiceImpl implements IIssueService {
    private final IssueRepository issues; private final IssueAuditRepository audits; private final ProjectRepository projects; private final ModuleRepository modules;
    public IssueServiceImpl(IssueRepository i, IssueAuditRepository a, ProjectRepository p, ModuleRepository m){issues=i;audits=a;projects=p;modules=m;}
    public PageResponse<IssueResponseDto> list(UserEntity a,long project,String q,IssueStage stage,IssueType type,IssuePriority priority,Long module,int page,int size){scope(a,project);var p=PageRequest.of(Math.max(0,page),Math.min(Math.max(1,size),100));return PageResponse.of(issues.search(project,q==null?"":q.trim(),stage,type,priority,module,p).map(this::map));}
    public IssueResponseDto get(UserEntity a,long id){var i=issues.findById(id).orElseThrow();scope(a,i.getProjectId());return map(i);}
    @Transactional public IssueResponseDto create(UserEntity a,CreateIssueRequest r){scope(a,r.projectId());if(r.moduleId()!=null){var module=modules.findById(r.moduleId()).orElseThrow(()->new NoSuchElementException("Module not found"));if(module.getProjectId()!=r.projectId())throw new IllegalArgumentException("Module does not belong to project");}var saved=issues.save(new IssueEntity(r.title().trim(),r.description(),r.type(),r.priority(),r.projectId(),r.moduleId(),a.getId()));audits.save(new IssueAuditEntity(saved.getId(),a.getId(),"CREATED",null,null,null));return map(saved);}
    @Transactional public IssueResponseDto update(UserEntity a,long id,UpdateIssueRequest r){var i=issues.findById(id).orElseThrow();scope(a,i.getProjectId());if(a.getRole()==UserRole.CLIENT_USER&&i.getReporterId()!=a.getId())throw new AccessDeniedException("Only the reporter may edit this issue");if(!Objects.equals(i.getTitle(),r.title()))audit(i,a,"title",i.getTitle(),r.title());if(!Objects.equals(i.getDescription(),r.description()))audit(i,a,"description",i.getDescription(),r.description());if(i.getType()!=r.type())audit(i,a,"type",i.getType().name(),r.type().name());if(i.getPriority()!=r.priority())audit(i,a,"priority",i.getPriority().name(),r.priority().name());i.setTitle(r.title().trim());i.setDescription(r.description());i.setType(r.type());i.setPriority(r.priority());return map(issues.save(i));}
    @Transactional public IssueResponseDto move(UserEntity a,long id,IssueStage stage){var i=issues.findById(id).orElseThrow();scope(a,i.getProjectId());if(a.getRole()==UserRole.CLIENT_USER){if(i.getReporterId()!=a.getId()||i.getStage()!=IssueStage.SUBMITTED||!(stage==IssueStage.DECLINED||stage==IssueStage.RESOLVED))throw new AccessDeniedException("Issue stage transition denied");}else if(!validTransition(i.getStage(),stage))throw new IllegalArgumentException("Invalid issue stage transition");IssueStage old=i.getStage();i.setStage(stage);audit(i,a,"stage",old.name(),stage.name());return map(issues.save(i));}
    @Transactional public IssueResponseDto requestVerification(UserEntity a,long id){var i=issues.findById(id).orElseThrow();scope(a,i.getProjectId());if(a.getRole()==UserRole.CLIENT_USER&&i.getReporterId()!=a.getId())throw new AccessDeniedException("Only the reporter may request verification");i.setVerificationStatus(VerificationStatus.PENDING_VERIFICATION);audit(i,a,"verificationStatus",null,VerificationStatus.PENDING_VERIFICATION.name());return map(issues.save(i));}
    public List<IssueResponseDto> verificationQueue(UserEntity a){if(a.getRole()==UserRole.CLIENT_USER)throw new AccessDeniedException("Verification access denied");return issues.findByVerificationStatus(VerificationStatus.PENDING_VERIFICATION).stream().filter(i->a.getRole()==UserRole.APP_ADMIN||projects.member(i.getProjectId(),a.getId())).map(this::map).toList();}
    @Transactional public IssueResponseDto approve(UserEntity a,long id,VerificationDecisionRequest r){var i=verificationTarget(a,id);var old=i.getVerificationStatus();i.setVerificationStatus(VerificationStatus.ACCEPTED);audit(i,a,"verificationStatus",old.name(),VerificationStatus.ACCEPTED.name());if(i.getStage()==IssueStage.TESTING){audit(i,a,"stage",i.getStage().name(),IssueStage.DEPLOYED.name());i.setStage(IssueStage.DEPLOYED);}return map(issues.save(i));}
    @Transactional public IssueResponseDto reject(UserEntity a,long id,VerificationDecisionRequest r){var i=verificationTarget(a,id);var old=i.getVerificationStatus();i.setVerificationStatus(VerificationStatus.REJECTED);audit(i,a,"verificationStatus",old.name(),VerificationStatus.REJECTED.name());audit(i,a,"verificationReason",null,r.reason());i.setStage(IssueStage.UNDER_DEVELOPMENT);return map(issues.save(i));}
    public List<IssueAuditResponseDto> audit(UserEntity a,long id){var i=issues.findById(id).orElseThrow();scope(a,i.getProjectId());return audits.findByIssueIdOrderByCreatedAtAsc(id).stream().map(x->new IssueAuditResponseDto(x.getId(),x.getIssueId(),x.getActorId(),x.getAction(),x.getFieldName(),x.getOldValue(),x.getNewValue(),x.getCreatedAt())).toList();}
    private IssueEntity verificationTarget(UserEntity a,long id){var i=issues.findById(id).orElseThrow();if(a.getRole()==UserRole.CLIENT_USER)throw new AccessDeniedException("Verification access denied");scope(a,i.getProjectId());if(i.getVerificationStatus()!=VerificationStatus.PENDING_VERIFICATION)throw new IllegalArgumentException("Issue is not pending verification");return i;}
    private boolean validTransition(IssueStage from,IssueStage to){return (from==IssueStage.SUBMITTED&&(to==IssueStage.RECEIVED||to==IssueStage.DECLINED))||(from==IssueStage.RECEIVED&&to==IssueStage.UNDER_DEVELOPMENT)||(from==IssueStage.UNDER_DEVELOPMENT&&to==IssueStage.TESTING)||(from==IssueStage.TESTING&&to==IssueStage.DEPLOYED)||(to==IssueStage.RESOLVED&&(from!=IssueStage.DEPLOYED&&from!=IssueStage.DECLINED));}
    private void audit(IssueEntity i,UserEntity a,String field,String oldV,String newV){audits.save(new IssueAuditEntity(i.getId(),a.getId(),"UPDATED",field,oldV,newV));}
    private void scope(UserEntity a,long project){if(a.getRole()==UserRole.APP_ADMIN||projects.member(project,a.getId()))return;throw new AccessDeniedException("Project access denied");}
    private IssueResponseDto map(IssueEntity i){return new IssueResponseDto(i.getId(),i.getTitle(),i.getDescription(),i.getType(),i.getPriority(),i.getStage(),i.getVerificationStatus(),i.getProjectId(),i.getModuleId(),i.getReporterId(),i.getCreatedAt(),i.getUpdatedAt());}
}
