CREATE TABLE issues (
 id BIGINT NOT NULL AUTO_INCREMENT, title VARCHAR(240) NOT NULL, description TEXT NOT NULL,
 type VARCHAR(30) NOT NULL, priority VARCHAR(30) NOT NULL, stage VARCHAR(40) NOT NULL,
 verification_status VARCHAR(30) NOT NULL DEFAULT 'NOT_REQUIRED', project_id BIGINT NOT NULL,
 module_id BIGINT NULL, reporter_id BIGINT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id), FOREIGN KEY(project_id) REFERENCES projects(id), FOREIGN KEY(module_id) REFERENCES modules(id), FOREIGN KEY(reporter_id) REFERENCES users(id)
);
CREATE TABLE issue_audits (
 id BIGINT NOT NULL AUTO_INCREMENT, issue_id BIGINT NOT NULL, actor_id BIGINT NOT NULL,
 action VARCHAR(40) NOT NULL, field_name VARCHAR(80), old_value TEXT, new_value TEXT,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id),
 FOREIGN KEY(issue_id) REFERENCES issues(id), FOREIGN KEY(actor_id) REFERENCES users(id)
);
